name: Deploy on PyPi

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'

jobs:
  job_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Tag info
        id: branch_info
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check version
        run: |
          echo "Tag: ${SOURCE_TAG}"
          VERSION=$(python3 setup.py --version)
          echo "Version: ${VERSION}"
          if [ $VERSION == $SOURCE_TAG ]; then exit 0; else exit 1; fi

        env:
          SOURCE_TAG: ${{ steps.branch_info.outputs.SOURCE_TAG }}

      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          pip install setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
