name: Fast checks

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  ruff:
    name: Checks & format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff - lint check
        uses: astral-sh/ruff-action@v3
      - name: Ruff - format check
        run: ruff format --check

  mypy:
    name: Python type checking
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install mypy types-setuptools types-requests
      - name: Mypy type checking
        run: mypy ledgercomm

  bandit:
    name: Security checking
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install bandit
      - name: Bandit security checking
        run: bandit -r ledgercomm -ll

  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check misspellings
        uses: codespell-project/actions-codespell@v1
        with:
          builtin: clear,rare
          check_filenames: true
